Fix various typos/docstring fmt problems, fetch with PEP8 standard.
djkcyl/BBot-Graia pull request #19
Opened 2022-09-10 14:51 UTC by GBLodb

2022-09-10 15:12 UTC, GreyElaina commented
wtf, a lot cannot work.

2022-09-10 15:15 UTC, Redlnn commented
正在 review 不要 force push 谢谢

2022-09-10 15:18 UTC, Redlnn requested changes

2022-09-10 15:18 UTC, Redlnn commented on function/command/video_resolve.py
> +        except (Exception,):
为什么需要这么做？如果是为了编辑器的话，我觉得 `# noqa` 好点

2022-09-10 15:18 UTC, Redlnn commented on function/pusher/dynamic.py
> +@channel.use(SchedulerSchema(every_custom_seconds(1)))
A60曾说：“我要刷爆B站服务器”，然后这里 IDE 报错其实是正常的，type hint 有问题而已

2022-09-10 15:18 UTC, Redlnn commented on function/pusher/init.py
> +    pass
这样不行，建议读 Ariadne 文档

2022-09-10 15:18 UTC, Redlnn commented on main.py
> -import bot
？那怎么启动bot，建议先读一下源码

2022-09-10 15:20 UTC, BlueGlassBlock requested changes

2022-09-10 15:20 UTC, BlueGlassBlock commented on core/bot_config.py
> -    def specification_groups(cls, groups):
intended usage of pydantic

2022-09-10 15:20 UTC, BlueGlassBlock commented on core/bot_config.py
> +        except KeyError as keyerr:
反而会被认为是 incorrectly spelled 的单词

2022-09-10 15:20 UTC, BlueGlassBlock commented on core/subgroup_config.py
> -    def __init__(self, group_name: str):
同上，进一步导致 spell checker 报错

2022-09-10 15:20 UTC, BlueGlassBlock commented on function/command/video_resolve.py
> +        except (Exception,):
完全没有必要。。。

2022-09-10 15:20 UTC, BlueGlassBlock commented on function/pusher/init.py
> +            subid_list[i: i + BotConfig.Bilibili.concurrency]
black 更适合些。。。

2022-09-10 15:20 UTC, BlueGlassBlock commented on function/pusher/init.py
> +async def detected_event(app: Ariadne, friend: Friend, message: MessageChain):
这真的能work吗（框架开发的质疑）

2022-09-10 15:20 UTC, BlueGlassBlock commented
在完成前请不要直接open PR

2022-09-10 15:20 UTC, BlueGlassBlock commented
draft 会更合适些

2022-09-10 15:21 UTC, GBLodb commented
草 没看 conversation

2022-09-10 15:26 UTC, GBLodb commented on function/pusher/init.py
> +            subid_list[i: i + BotConfig.Bilibili.concurrency]
https://www.flake8rules.com/rules/E203.html

2022-09-10 15:28 UTC, GBLodb commented on function/command/video_resolve.py
> +        except (Exception,):
这么说确实不如直接 ``# noqa``

2022-09-10 15:34 UTC, MingxuanGame commented on function/command/configure/atall.py
> +    msg = None
别用 None，会导致类型检查器报错，用空字符串或者将第 47 行的

```python
elif acts == "关闭":
```

改成 else

2022-09-10 15:35 UTC, MingxuanGame commented on function/command/configure/nick.py
> +    msg = None
同上，第 51 行

```python
elif acts == "删除":
```

换成 else

2022-09-10 15:48 UTC, MingxuanGame commented on function/command/configure/atall.py
> +    msg = ""
这个可以直接删掉了，下面未使用（同下 nick.py）

2022-09-10 15:52 UTC, GBLodb commented
除了[这里](https://github.com/djkcyl/BBot-Graia/pull/19#discussion_r967665982)还需要确认以外都处理完了

没有其他问题我就最后 force push 一次了

一开始没看 conversation 还忘 draft 给各位造成麻烦了抱歉(

2022-09-10 15:58 UTC, Redlnn commented
> 除了[这里](https://github.com/djkcyl/BBot-Graia/pull/19#discussion_r967665982)还需要确认以外都处理完了
> 
> 没有其他问题我就最后 force push 一次了
> 
> 一开始没看 conversation 还忘 draft 给各位造成麻烦了抱歉(

为什么要 force push，前面的 review 全乱了，多个 commit 可以合并为一个再 merge 的

2022-09-10 16:00 UTC, GBLodb commented
> > 除了[这里](https://github.com/djkcyl/BBot-Graia/pull/19#discussion_r967665982)还需要确认以外都处理完了
> > 没有其他问题我就最后 force push 一次了
> > 一开始没看 conversation 还忘 draft 给各位造成麻烦了抱歉(
> 
> 为什么要 force push，前面的 review 全乱了，多个 commit 可以合并为一个再 merge 的

习惯性 amend/force push 了 没考虑到 review 还是再次抱歉

2022-09-10 16:01 UTC, Redlnn commented on function/pusher/init.py
> +            subid_list[i: i + BotConfig.Bilibili.concurrency]
bbot 使用 black，以 black 为准，请本地执行 `poetry run black .` 格式化所有代码后 commit

2022-09-10 16:03 UTC, Redlnn commented on function/pusher/init.py
> +            subid_list[i: i + BotConfig.Bilibili.concurrency]
> bbot 使用 black，以 black 为准，请本地执行 `poetry run black .` 格式化所有代码后 commit

如果 black 对两种都没意见，再参考 flake8 和 pep8

2022-09-10 16:15 UTC, Redlnn commented on function/pusher/init.py
> +    pass
这里的 `pass` 是否无意义了？

2022-09-10 18:31 UTC, BlueGlassBlock approved these changes

2022-09-10 23:02 UTC, MingxuanGame approved these changes

2022-09-11 03:49 UTC, djkcyl approved these changes

2022-09-11 04:37 UTC, Redlnn approved these changes

2022-09-11 09:40 UTC, merged